### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by omatty198** [omatty198/iOSTraning#1]
### 導入
- [ ] Objective C の基礎
- [ ] メモリ管理
- [ ] UIViewController1 - UIViewController のカスタマイズ
- [ ] UIViewController2 - ModalViewController
- [ ] UIViewController3 - ライフサイクル
- [ ] HomeWork 1 Objective C の基本文法
- [ ] HomeWork 2 UIViewControllerとModalViewController
- [ ] HomeWork 3 UIViewController ＋ Animation

### UIKit 1 - container, rotate-
- [ ] UINavigationController
- [ ] UITabController
- [ ] Custom Container View Controller
- [ ] Supporting Multiple Interface Orientations
- [ ] HomeWork 1 - タブバーからモーダルビューを表示する
- [ ] HomeWork 2 - NavigationController
- [ ] HomeWork 2.3 デバイスことに回転対応

### UIKit 2- UIView -
- [ ] UIView
- [ ] UIView のカスタマイズ
- [ ] UIView Animation
- [ ] HomeWork 1 - UIScrollView

### UIKit 3 - table view -
- [ ] UITableView について
- [ ] UITableViewとNavigationController
- [ ] custom UITableViewCell の作成
- [ ] UITableViewのその他のオプション、カスタマイズ
- [ ] HomeWork 1 - Dynamic height with a custom uitableviewcell

### UIKit 4 - image and text -
- [ ] UIImagePickerController
- [ ] Assets Library
- [ ] UITextFiled, UITextView
- [ ] KeyboardNotification
- [ ] Homework 1 - フォトの複数枚選択

### 6.ネットワーク処理
- [ ] NSURLConnection
- [ ] JSONのシリアライズとデシリアライズ
- [ ] UIWebView

### 7.ローカルキャッシュと通知
- [ ] NSUserDefaults, Settings Bundle
- [ ] NSFileManager
- [ ] Key Value Observing
- [ ] NSNotification、NSNotificationCenter を用いた通知

### 8.Blocks, GCD
- [ ] Blocks
- [ ] GCD
- [ ] 【演習】GCD,-Blocksを用いたHTTPリクエストマネージャの作成

### 9.設計とデザインパターン
- [ ] クラス設計 1
- [ ] クラス設計 2
- [ ] クラス設計演習

### 10.開発ツール
- [ ] Instruments, デバッガ
- [ ] CocoaPods

### テスト
- [ ]  iOS開発におけるテスト
- [ ] GHUnit
- [ ] Kiwi
- [ ] KIF

### In-App Purchase
- [ ] In-App Purchase
